# Generated by Django 5.0.7 on 2026-06-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacefile',
            name='is_binary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacefile',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
